### ISSUE TITLE
Name changes

### ISSUE THREAD

**Issue by worksofliam** [NielsLiisberg/Node.RPG#1]
Hi

Everyone I have shared this with is initially confused about what the project does because of the word 'Node' being in the project name.

This is a long shot but it might be worth renaming to something more relevent. Perhaps `micro.RPG` for 'microservices in RPG'.

Thanks!

**Comment by mlitters** [comment]
I think the name is not bad at all because Niels is right when he says he wanted to create something as simple as Node.js but for RPG.
And I can imagine that more people will take a look on it because of this name. 
But as we all know - names are a matter of taste. I remeber a server once called AS/400, iSeries, i5, System i ...
